// <auto-generated />
using advertisingAgency;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace advertisingAgency.Migrations
{
    [DbContext(typeof(adAgencyContext))]
    [Migration("20180219103242_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("advertisingAgency.Advedirsments", b =>
                {
                    b.Property<int>("AdvedirsmentsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdDescription");

                    b.Property<string>("AdType");

                    b.HasKey("AdvedirsmentsId");

                    b.ToTable("Advedirsments");
                });

            modelBuilder.Entity("advertisingAgency.Customers", b =>
                {
                    b.Property<int>("CustomersId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerAddress");

                    b.Property<string>("CustomerName");

                    b.Property<string>("CustomerTelephone");

                    b.HasKey("CustomersId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("advertisingAgency.Orders", b =>
                {
                    b.Property<int>("OrdersId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AdvedirsmentsId");

                    b.Property<int?>("CustomersId");

                    b.Property<DateTime>("DataBegin");

                    b.Property<DateTime>("DataEnd");

                    b.Property<DateTime>("DataOrder");

                    b.Property<int>("EmployeeId");

                    b.Property<string>("ListOfServices");

                    b.Property<string>("Location");

                    b.Property<int>("OrderCost");

                    b.Property<bool>("PaymentStatus");

                    b.HasKey("OrdersId");

                    b.HasIndex("AdvedirsmentsId");

                    b.HasIndex("CustomersId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("advertisingAgency.Orders", b =>
                {
                    b.HasOne("advertisingAgency.Advedirsments", "Advedirsments")
                        .WithMany("Orders")
                        .HasForeignKey("AdvedirsmentsId");

                    b.HasOne("advertisingAgency.Customers", "Customers")
                        .WithMany("Orders")
                        .HasForeignKey("CustomersId");
                });
#pragma warning restore 612, 618
        }
    }
}
